# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        ('MarketApp', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1)),
                ('c_status', models.BooleanField(default=1)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.Goods')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Users')),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
    ]
